# Labeler-Konfiguration für HypnoScript
# See https://github.com/actions/labeler for configuration format.

'area:core':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-core/**'

'area:lexer-parser':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-lexer-parser/**'

'area:compiler':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-compiler/**'

'area:runtime':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-runtime/**'

'area:cli':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-cli/**'

'area:documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-docs/**'
          - '*.md'
          - '**/*.md'

'area:testing':
  - changed-files:
      - any-glob-to-any-file:
          - 'hypnoscript-tests/**'
          - '**/*.hyp'

'area:ci':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

'area:tooling':
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - 'release/**'
          - 'package.json'
          - 'package-lock.json'

'area:workspace':
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - '**/Cargo.toml'
          - 'deny.toml'

'branch:main-target':
  - base-branch:
      - '^main$'

'branch:dev-target':
  - base-branch:
      - '^(dev|development)$'

'branch:release-target':
  - base-branch:
      - '^(release|release[-/].+)$'

'type:feature':
  - head-branch:
      - '^(?:[Ff][Ee][Aa][Tt][Uu][Rr][Ee]|[Ff][Ee][Aa][Tt])[-/].+'

'type:task':
  - head-branch:
      - '^(?:[Tt][Aa][Ss][Kk]|[Cc][Hh][Oo][Rr][Ee])[-/].+'

'type:release':
  - head-branch:
      - '^[Rr][Ee][Ll][Ee][Aa][Ss][Ee][-/].+'

'type:bugfix':
  - head-branch:
      - '^(?:[Bb][Uu][Gg][Ff][Ii][Xx]|[Ff][Ii][Xx])[-/].+'

'type:hotfix':
  - head-branch:
      - '^[Hh][Oo][Tt][Ff][Ii][Xx][-/].+'
