using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml.Linq;

namespace HypnoScript.Runtime.Builtins
{
    /// <summary>
    /// Simple documentation generator for Builtins. Scans all Builtins/*.cs files and generates Markdown docs.
    /// </summary>
    public static class DocGenerator
    {
        public static void GenerateMarkdownDocs(string outputDir)
        {
            var builtinsDir = Path.GetDirectoryName(typeof(DocGenerator).Assembly.Location);
            var builtinTypes = Assembly.GetExecutingAssembly().GetTypes()
                .Where(t => t.IsClass && t.IsPublic && t.Namespace == "HypnoScript.Runtime.Builtins")
                .ToList();
            foreach (var type in builtinTypes)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"# {type.Name.Replace("Builtins", " Functions")}");
                sb.AppendLine();
                foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Static))
                {
                    sb.AppendLine($"## {method.Name}");
                    sb.AppendLine();
                    sb.AppendLine($"**Signature:** `{method}`");
                    sb.AppendLine();
                    // Try to get XML doc comment (if available)
                    var xmlComment = GetXmlDocComment(type, method);
                    if (!string.IsNullOrWhiteSpace(xmlComment))
                        sb.AppendLine(xmlComment);
                    else
                        sb.AppendLine($"_No description available._");
                    sb.AppendLine();
                }
                var outFile = Path.Combine(outputDir, $"{type.Name.Replace("Builtins", "").ToLowerInvariant()}-functions.md");
                File.WriteAllText(outFile, sb.ToString());
            }
        }

        private static string? GetXmlDocComment(Type type, System.Reflection.MethodInfo method)
        {
            // This is a stub. In a real implementation, parse the XML doc file generated by the compiler.
            // For now, return null.
            return null;
        }
    }
}
