[package]
name = "hypnoscript-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hypnoscript-core = { path = "../hypnoscript-core" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
csv = { workspace = true }
chrono = "0.4.43"
regex = "1.12.2"
num_cpus = "1.17.0"
hostname = "0.4.2"
sha2 = "0.10.9"
md5 = "0.8.0"
base64 = "0.22.1"
uuid = { version = "1.19.0", features = ["v4"] }
