/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Einführung',
    },
    {
      type: 'category',
      label: 'Erste Schritte',
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/hello-world',
        'getting-started/cli-basics',
      ],
    },
    {
      type: 'category',
      label: 'Sprachreferenz',
      items: [
        'language-reference/syntax',
        'language-reference/variables',
        'language-reference/data-types',
        'language-reference/operators',
        'language-reference/control-flow',
        'language-reference/functions',
        'language-reference/sessions',
        'language-reference/tranceify',
        'language-reference/arrays',
        'language-reference/records',
        'language-reference/imports',
        'language-reference/assertions',
      ],
    },
    {
      type: 'category',
      label: 'Builtin-Funktionen',
      items: [
        'builtins/overview',
        'builtins/array-functions',
        'builtins/string-functions',
        'builtins/math-functions',
        'builtins/utility-functions',
        'builtins/system-functions',
        'builtins/time-date-functions',
        'builtins/statistics-functions',
        'builtins/hashing-encoding',
        'builtins/hypnotic-functions',
        'builtins/dictionary-functions',
        'builtins/file-functions',
        'builtins/network-functions',
        'builtins/validation-functions',
        'builtins/performance-functions',
      ],
    },
    {
      type: 'category',
      label: 'CLI & Tools',
      items: [
        'cli/overview',
        'cli/commands',
        'cli/configuration',
        'cli/testing',
        'cli/debugging',
        'cli/enterprise-features',
      ],
    },
    {
      type: 'category',
      label: 'Beispiele',
      items: [
        'examples/basic-examples',
        'examples/array-examples',
        'examples/string-examples',
        'examples/math-examples',
        'examples/file-examples',
        'examples/hypnotic-examples',
        'examples/advanced-examples',
      ],
    },
    {
      type: 'category',
      label: 'Entwicklung',
      items: [
        'development/architecture',
        'development/contributing',
        'development/building',
        'development/testing',
        'development/debugging',
        'development/extending',
      ],
    },
    {
      type: 'category',
      label: 'Referenz',
      items: [
        'reference/grammar',
        'reference/ast',
        'reference/interpreter',
        'reference/compiler',
        'reference/runtime',
        'reference/api',
        'changelog',
      ],
    },
  ],
};

module.exports = sidebars;
